### PR TITLE
predicting whole sentence in one shot

### PR DESCRIPTION
**Pull request by liuhuang31**
The dataloader has also been modified accordingly, some text feature extraction operations do not require multiple for loops. Finally, it was changed into a whole sentence of direct prediction

### CODE REVIEW

**Comment by GitYCC** [comment]
Because the PR aim to enhance the tool, I look forward to update the new feature based on old codes.

**Comment by liuhuang31** [comment]
> 1. using

That's a good idea, I'm looking forward to it.

**Comment by GitYCC** [comment]
@liuhuang31 
Please base on latest `develop` branch to admit and merge to `develop` branch by PR.
I close this PR at first.

**Comment by GitYCC** [comment]
@liuhuang31 
Please base on latest `develop` branch to admit and merge to `develop` branch by PR.
I close this PR at first.

**Comment by GitYCC** [comment]
@liuhuang31
I think there has a problem that you set `window_size = None` because it cause difference between training time and inference time. ref: https://github.com/GitYCC/g2pW/issues/7#issuecomment-1211654717

**Comment by liuhuang31** [comment]
> 
First,  use larger batch_size can speed, but still too slow. Time cost modules or options are dataloder and bert_prediction.

**Comment by GitYCC** [comment]
@liuhuang31 
I think I'm persuaded by you and look forward your PR.
I appreciate that 
1. inherit `TextDataset` to create `TextDatasetOneShot` (overwrite `__getitem__` and `create_mini_batch`)
2. inherit `G2PW` to create `G2PWOneShot` (overwrite `forward`)
3. put `TextDatasetOneShot` and `G2PWOneShot` into `api.py` because they are used for the package 

Thank you!

**Comment by GitYCC** [comment]
@liuhuang31 
Are you free to complete this PR in the next week? If not, could I take this PR?

**Comment by liuhuang31** [comment]
@GitYCC 

Of course, just do it. I'm looking forward your updates.

**Comment by GitYCC** [comment]
@liuhuang31 
Okay! But I will fork from latest `develop` and update codes.

**Pull request closed without merging**
